id = "pinescript"
name = "Pine Script"
description = "Pine Script language support for Zed - syntax highlighting for TradingView's Pine Script"
version = "0.1.0"
schema_version = 1
authors = ["Tinz Leung <your.email@example.com>"]
repository = "https://github.com/Pvxlabs/pine-script-zed.git"

[grammars.pine]
repository = "https://github.com/Pvxlabs/pine-script-zed.git"
path = "vendor/tree-sitter-pine"
rev = "2c6822499f3d525e167bfa7bcb0bb3db0f28c45d"
